import { type NextPage } from "next";
import Head from "next/head";
import { trpc } from "../utils/trpc";
import Collapsable from "./components/Collapsable";

const Home: NextPage = () => {


  return (
    <>
      <Head>
        <title>Test assign</title>
        <meta name="description" content="Generated by create-t3-app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className="flex min-h-screen flex-col items-center justify-center bg-[#D2E1FF]">
      <Collapsable />
      </main>
    </>
  );
};

export default Home;

